name: test

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "repo"
        default: "tile-ai/tilelang"
      branch:
        description: "branch"
        default: "main"
      link:
        description: "download link"
      version:
        description: "release version"
  # schedule:
  #   - cron: '0 2 * * *'

jobs:
  release:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: |
          mkdir -p dist
          wget -O wheel.zip "${{ inputs.link }}"
          unzip wheel.zip -d dist/
      - run: ls -lah dist/
      
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          files: dist/*
          token: ${{ secrets.GITHUB_TOKEN }} 
      
      - name: Clone wheel index
        run: git clone https://$WHL_TOKEN@github.com/tile-ai/whl.git tilelang-whl
        env:
          WHL_TOKEN: ${{ secrets.WHL_TOKEN }}
  
      - name: Update wheel index
        run: python3 update_whl_index.py
  
      - name: Push wheel index
        run: |
          cd tilelang-whl
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "update nightly whl"
          git push https://github-actions[bot]:$WHL_TOKEN@github.com/tile-ai/whl.git main
        env:
          WHL_TOKEN: ${{ secrets.WHL_TOKEN }}
